In [10]:
import numpy as np
from tqdm import tqdm
from numba import jit
import time


def f(t):
    u=0
    for k in tqdm(range(0,100)):
        for i in range(0,10000000):
            if k==0:
                u=t
            else:
                u+=i
    return u
with timer():
    print(f(0))

AttributeError: __exit__

In [25]:
import numpy as np
t=np.zeros((6,3))
t[0:6, 1]=[1,2,3,4,5,6]
print(t)
y=t[4,:]
print(y)
print(y.shape)

m = np.vstack((t,y))
print(m)
y=t[:,1]
print(y)
r=[]
r.append(y)
r.append(y)
u=np.array(r)
print(u)

a=[0,1,2]
b=[2,3,4]
t=np.stack((a,b))
print(t)

[[0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]
 [0. 4. 0.]
 [0. 5. 0.]
 [0. 6. 0.]]
[0. 5. 0.]
(3,)
[[0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]
 [0. 4. 0.]
 [0. 5. 0.]
 [0. 6. 0.]
 [0. 5. 0.]]
[1. 2. 3. 4. 5. 6.]
[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]
[[0 1 2]
 [2 3 4]]


In [10]:
import numpy as np
import tqdm

u=0
for i in tqdm.tqdm(range(int(10000000))):
    u+=i
print(u)

100%|█████████████████████████████████████████████████████████████████| 10000000/10000000 [00:03<00:00, 3174143.97it/s]

49999995000000


In [4]:
import numpy as np
import os, os.path
import sys

from datetime import datetime
import time

from selenium import webdriver

driver = webdriver.Chrome('./chromedriver')


OSError: [WinError 193] %1 は有効な Win32 アプリケーションではありません。

In [1]:
import timeit
from numba import jit

@jit
def ack(m, n):
    if m == 0:
        return n + 1
    if n == 0:
        return ack(m - 1, 1)
    
    return ack(m - 1, ack(m, n - 1))
py=timeit.timeit('ack(4,0)', globals=globals(), number=1)
print(py)
print(ack(4,0))


0.214549
13


In [11]:

from contextlib import contextmanager




@contextmanager
def timer():
    t = time.perf_counter()
    yield None
    print('Elapsed:', time.perf_counter() - t)
    
py=timeit.timeit('ack(3,8)',number=1000)
print(py)

NameError: name 'ack' is not defined

In [25]:
from numba import jit
import cython
%load_ext Cython

cdef int ack(int m, int n):
    if m == 0:
        return n + 1
    if n == 0:
        return ack(m - 1, 1)
    return ack(m - 1, ack(m, n - 1))

# 1回目
with timer():
    print(ack(3, 8))

# 2回目
with timer():
    print(ack(3, 8))

# 3回目
with timer():
    print(ack(3, 8))

SyntaxError: invalid syntax (<ipython-input-25-09abd0f7f0fe>, line 6)

In [36]:
%%cython
cpdef int myfunction(int x, int y=2):
    cdef int a = x - y
    return a + x * y

cdef double _helper(double a):
    return a + 1

cdef class A:
    cdef public int x
    cdef public int y
    cdef double _scale
    cdef readonly float read_only

    def __init__(self, int b=0):
        self.a = 3
        self.b = b
        self._scale = 2.0
        self.read_only = 1.0

    cpdef double foo(self, double x):
        return (x + _helper(1.0)) * self._scale

TypeError: dist must be a Distribution instance

In [27]:
def primes(nb_primes: cython.int):
    i: cython.int
    p: cython.int[1000]

    if nb_primes > 1000:
        nb_primes = 1000

    if not cython.compiled:  # Only if regular Python is running
        p = [0] * 1000       # Make p work almost like a C array

    len_p: cython.int = 0  # The current number of elements in p.
    n: cython.int = 2
    while len_p < nb_primes:
        # Is n prime?
        for i in p[:len_p]:
            if n % i == 0:
                break

        # If no break occurred in the loop, we have a prime.
        else:
            p[len_p] = n
            len_p += 1
        n += 1

    # Let's copy the result into a Python list:
    result_as_list = [prime for prime in p[:len_p]]
    return result_as_list

SyntaxError: invalid syntax (<ipython-input-27-c539c3049e8b>, line 2)

In [37]:
%load_ext Cython

The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython


In [38]:
%%cython -n test_cython_code
def fib(int n):
    cdef int i
    cdef double a=0.0, b=1.0

    for i in range(n):
        a, b = a+b, a
    return a

def primes(int kmax):
    cdef int n, k, i
    cdef int p[1000]
    result = []

    if kmax > 1000:
        kmax = 1000

    k = 0
    n = 2
    while k < kmax:
        i = 0
        while i < k and n % p[i] != 0:
            i += 1

        if i == k:
            p[k] = n
            k += 1
            result.append(n)
        n += 1
    return result

TypeError: dist must be a Distribution instance

In [39]:
%%cython -+

cdef cypclass Int:
    int value

    __init__(self, int value):
        self.value = value

    object __repr__(self) with gil:
        return "cypclass integer %d" % self.value

print(Int(42))


Error compiling Cython file:
------------------------------------------------------------
...

cdef cypclass Int:
    int value
       ^
------------------------------------------------------------

C:\Users\haruna\.ipython\cython\_cython_magic_f7bcc3fdcd18d5e617ea3013052b355b.pyx:3:8: Syntax error in simple statement list


TypeError: object of type 'NoneType' has no len()

In [40]:
import setuptools  # important
from distutils.core import setup
from Cython.Build import cythonize
setup(ext_modules=cythonize("module1.pyx", build_dir="build"),
                                           script_args=['build'], 
                                           options={'build':{'build_lib':'.'}})

ValueError: 'module1.pyx' doesn't match any files

In [41]:
%%cython -a
def cyfib(int n):
    a, b = 0.0, 1.0
    for i in range(n):
        a, b = a + b, a
    return a


TypeError: dist must be a Distribution instance

In [16]:
import timeit

def test(n):
    return sum(range(n))

n = 10000
loop = 1000

result = timeit.timeit('test(n)', globals=globals(), number=loop)
print(result / loop)

0.000169979499999954


In [18]:
import tensorflow as tf
import numpy
import matplotlib.pyplot as plt
%matplotlib qt
 
 
rng = numpy.random

L = 20
step = rng.choice([-0.1,0.1],L)
random_walk = numpy.cumsum(step)
 
# 20分間のデータ作成
train_X = numpy.linspace(1,20,num=20)
train_Y = numpy.linspace(110,112,num=20)
train_X = numpy.asarray(train_X)
train_Y = numpy.asarray(train_Y)
train_Y = train_Y - random_walk
n_samples = train_X.shape[0]

plt.plot(train_X, train_Y, 'ro', label='Low Price')
plt.grid(True)
plt.legend()
plt.show()

learning_rate = 0.1
training_epochs = 1000
 
# コスト表示のための回数区切り
display_step = 200


X = tf.placeholder("float", name='X')
Y = tf.placeholder("float", name='Y')
 
# Set model weights
W = tf.Variable(rng.randn(), name="weight")
b = tf.Variable(rng.randn(), name="bias")

pred = tf.add(tf.multiply(X, W), b, name='pred')
 
# コスト関数（ 平均二乗誤差 -MSE ）
cost = tf.reduce_sum(tf.pow(pred-Y, 2), name='cost')/(2*n_samples)
 
# 最急降下法
optimizer = tf.train.GradientDescentOptimizer(learning_rate, name='optimizer').minimize(cost)
 
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for epoch in range(training_epochs):
    for (x, y) in zip(train_X, train_Y):
        sess.run(optimizer, feed_dict={X:x, Y: y})
 
    if (epoch+1) % display_step == 0:
        c = sess.run(cost, feed_dict={X: train_X, Y:train_Y})
        print ("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), "W=", sess.run(W), "b=", sess.run(b))
 

Epoch: 0200 cost= 2.514369011 W= 0.28190216 b= 105.93024
Epoch: 0400 cost= 0.011507686 W= 0.097811274 b= 109.71159
Epoch: 0600 cost= 0.006164656 W= 0.09127621 b= 109.84583
Epoch: 0800 cost= 0.006082089 W= 0.09104858 b= 109.8505
Epoch: 1000 cost= 0.006074776 W= 0.09102722 b= 109.85094


In [22]:
plt.plot(train_X, train_Y, 'ro', label='Low Price')
plt.plot(train_X, sess.run(W) * train_X + sess.run(b), label='Trend line')
plt.grid(True)
plt.legend()
plt.show()

In [1]:
saver = tf.train.Saver()
saver.save(sess, './linear')

NameError: name 'tf' is not defined

In [37]:
sess = tf.Session()
 
# 訓練済みモデルのmetaファイルを読み込み
saver = tf.train.import_meta_graph('linear.meta')

saver.restore(sess,tf.train.latest_checkpoint('./'))

        
graph = tf.get_default_graph()
weight = graph.get_tensor_by_name("weight:0")
bias = graph.get_tensor_by_name("bias:0")

print(sess.run('weight:0'))
print(sess.run('bias:0'))

now = numpy.array(21)
pred = sess.run('weight:0') * now + sess.run('bias:0')
print(pred)

INFO:tensorflow:Restoring parameters from ./linear
-0.62538683
0.1230442
-13.010079316794872
